@echo off
setlocal enabledelayedexpansion

REM ------------------------------------
REM Resolve paths
REM ------------------------------------

set SCRIPT_DIR=%~dp0
set CORE_ROOT=%SCRIPT_DIR%..
set SCAFFOLD_DIR=%SCRIPT_DIR%scaffold
set TARGET_DIR=%cd%
set CORE_JSON=%CORE_ROOT%\agent-core.json

set GENERATED_DIR=%CORE_ROOT%\generated
set GENERATED_TASKS_DIR=%GENERATED_DIR%\tasks

REM ------------------------------------
REM Validate
REM ------------------------------------

if not exist "%CORE_JSON%" (
  echo agent-core.json not found. Aborting.
  exit /b 1
)

if not exist "%SCAFFOLD_DIR%" (
  echo scaffold directory not found. Aborting.
  exit /b 1
)

REM ------------------------------------
REM Read JSON (no dependencies)
REM ------------------------------------

for /f "tokens=2 delims=:," %%a in ('findstr /i "\"version\"" "%CORE_JSON%"') do (
    set VERSION=%%~a
    goto :version_done
)
:version_done

for /f "tokens=2 delims=:," %%a in ('findstr /i "\"schemaVersion\"" "%CORE_JSON%"') do (
    set SCHEMA_VERSION=%%~a
    goto :schema_done
)
:schema_done

for /f "tokens=2 delims=:," %%a in ('findstr /i "\"description\"" "%CORE_JSON%"') do (
    set DESCRIPTION=%%~a
    goto :desc_done
)
:desc_done

set VERSION=%VERSION:"=%
set SCHEMA_VERSION=%SCHEMA_VERSION:"=%
set DESCRIPTION=%DESCRIPTION:"=%

echo.
echo Installing Agent Core v%VERSION%
echo %DESCRIPTION%
echo Schema version: %SCHEMA_VERSION%
echo.

REM ------------------------------------
REM Prevent overwrite (parent only)
REM ------------------------------------

if exist "%TARGET_DIR%\AGENTS.md" (
  echo Error: AGENTS.md already exists. Aborting.
  exit /b 1
)

if exist "%TARGET_DIR%\CLAUDE.md" (
  echo Error: CLAUDE.md already exists. Aborting.
  exit /b 1
)

REM ------------------------------------
REM Install entrypoints to host project root
REM ------------------------------------

copy "%SCAFFOLD_DIR%\AGENTS.md" "%TARGET_DIR%\AGENTS.md" >nul
copy "%SCAFFOLD_DIR%\CLAUDE.md" "%TARGET_DIR%\CLAUDE.md" >nul

REM ------------------------------------
REM Provision runtime task surface inside agent-core\generated\
REM ------------------------------------

if not exist "%GENERATED_TASKS_DIR%" (
  mkdir "%GENERATED_TASKS_DIR%"
)

if not exist "%GENERATED_TASKS_DIR%\todo.md" (
  copy "%SCAFFOLD_DIR%\tasks\todo.md" "%GENERATED_TASKS_DIR%\todo.md" >nul
)

if not exist "%GENERATED_TASKS_DIR%\lessons.md" (
  copy "%SCAFFOLD_DIR%\tasks\lessons.md" "%GENERATED_TASKS_DIR%\lessons.md" >nul
)

REM ------------------------------------
REM Stamp generated entrypoints
REM ------------------------------------

echo.>> "%TARGET_DIR%\AGENTS.md"
echo --- >> "%TARGET_DIR%\AGENTS.md"
echo Generated by agent-core v%VERSION% >> "%TARGET_DIR%\AGENTS.md"

echo.>> "%TARGET_DIR%\CLAUDE.md"
echo --- >> "%TARGET_DIR%\CLAUDE.md"
echo Generated by agent-core v%VERSION% >> "%TARGET_DIR%\CLAUDE.md"

echo.
echo Agent Core installed.
echo.
echo Wrote:
echo   %TARGET_DIR%\AGENTS.md
echo   %TARGET_DIR%\CLAUDE.md
echo   %GENERATED_TASKS_DIR%\todo.md
echo   %GENERATED_TASKS_DIR%\lessons.md
echo.
echo Next steps:
echo   1. Commit AGENTS.md and CLAUDE.md.
echo   2. agent-core\generated\ is intentionally gitignored — do not commit.
echo   3. Read agent-core\INDEX.md before any change.
echo.
