@echo off
setlocal enabledelayedexpansion

REM ------------------------------------
REM Resolve paths
REM ------------------------------------

set SCRIPT_DIR=%~dp0
set CORE_ROOT=%SCRIPT_DIR%..
set SCAFFOLD_DIR=%SCRIPT_DIR%scaffold
set TARGET_DIR=%cd%
set CORE_JSON=%CORE_ROOT%\ai-agent-core.json

REM Host-owned state lives under <host>\.aiac\. The vendor tree
REM (ai-agent-core\) stays read-only.
set AIAC_DIR=%TARGET_DIR%\.aiac
set AIAC_TASKS_DIR=%AIAC_DIR%\tasks
set AIAC_CONFIG=%AIAC_DIR%\config.yml

set DOCS_DIR=%TARGET_DIR%\docs
set PROJECT_YML=%TARGET_DIR%\project.yml

REM ------------------------------------
REM Validate
REM ------------------------------------

if not exist "%CORE_JSON%" (
  echo ai-agent-core.json not found. Aborting.
  exit /b 1
)

if not exist "%SCAFFOLD_DIR%" (
  echo scaffold directory not found. Aborting.
  exit /b 1
)

REM ------------------------------------
REM Read JSON (no dependencies)
REM ------------------------------------

for /f "tokens=2 delims=:," %%a in ('findstr /i "\"version\"" "%CORE_JSON%"') do (
    set VERSION=%%~a
    goto :version_done
)
:version_done

for /f "tokens=2 delims=:," %%a in ('findstr /i "\"schemaVersion\"" "%CORE_JSON%"') do (
    set SCHEMA_VERSION=%%~a
    goto :schema_done
)
:schema_done

for /f "tokens=2 delims=:," %%a in ('findstr /i "\"description\"" "%CORE_JSON%"') do (
    set DESCRIPTION=%%~a
    goto :desc_done
)
:desc_done

set VERSION=%VERSION:"=%
set SCHEMA_VERSION=%SCHEMA_VERSION:"=%
set DESCRIPTION=%DESCRIPTION:"=%

echo.
echo Installing AI Agent Core v%VERSION%
echo %DESCRIPTION%
echo Schema version: %SCHEMA_VERSION%
echo.

REM ------------------------------------
REM Prevent overwrite (entrypoints only)
REM ------------------------------------

if exist "%TARGET_DIR%\AGENTS.md" (
  echo Error: AGENTS.md already exists. Aborting.
  exit /b 1
)

if exist "%TARGET_DIR%\CLAUDE.md" (
  echo Error: CLAUDE.md already exists. Aborting.
  exit /b 1
)

REM ------------------------------------
REM Install entrypoints to host project root
REM ------------------------------------

copy "%SCAFFOLD_DIR%\AGENTS.md" "%TARGET_DIR%\AGENTS.md" >nul
copy "%SCAFFOLD_DIR%\CLAUDE.md" "%TARGET_DIR%\CLAUDE.md" >nul

REM ------------------------------------
REM Install project.yml at host root (committed manifest)
REM ------------------------------------

if not exist "%PROJECT_YML%" (
  copy "%SCAFFOLD_DIR%\project.yml" "%PROJECT_YML%" >nul
)

REM ------------------------------------
REM Provision docs/ scaffold (Diataxis-extended)
REM Existing files are never overwritten.
REM ------------------------------------

if not exist "%DOCS_DIR%" mkdir "%DOCS_DIR%"
xcopy "%SCAFFOLD_DIR%\docs" "%DOCS_DIR%" /E /I /Y /D >nul

REM ------------------------------------
REM Provision .aiac\ (host-owned AI agent state)
REM .aiac\tasks\ is committed by default; hosts may gitignore it.
REM Existing files are never overwritten.
REM ------------------------------------

if not exist "%AIAC_DIR%" mkdir "%AIAC_DIR%"
if not exist "%AIAC_TASKS_DIR%" mkdir "%AIAC_TASKS_DIR%"

if not exist "%AIAC_CONFIG%" (
  copy "%SCAFFOLD_DIR%\.aiac\config.yml" "%AIAC_CONFIG%" >nul
)

if not exist "%AIAC_TASKS_DIR%\todo.md" (
  copy "%SCAFFOLD_DIR%\tasks\todo.md" "%AIAC_TASKS_DIR%\todo.md" >nul
)

if not exist "%AIAC_TASKS_DIR%\lessons.md" (
  copy "%SCAFFOLD_DIR%\tasks\lessons.md" "%AIAC_TASKS_DIR%\lessons.md" >nul
)

REM ------------------------------------
REM Stamp generated entrypoints
REM ------------------------------------

echo.>> "%TARGET_DIR%\AGENTS.md"
echo --- >> "%TARGET_DIR%\AGENTS.md"
echo Generated by ai-agent-core v%VERSION% >> "%TARGET_DIR%\AGENTS.md"

echo.>> "%TARGET_DIR%\CLAUDE.md"
echo --- >> "%TARGET_DIR%\CLAUDE.md"
echo Generated by ai-agent-core v%VERSION% >> "%TARGET_DIR%\CLAUDE.md"

echo.
echo AI Agent Core installed.
echo.
echo Wrote:
echo   %TARGET_DIR%\AGENTS.md
echo   %TARGET_DIR%\CLAUDE.md
echo   %PROJECT_YML%
echo   %DOCS_DIR%\ (Diataxis-extended scaffold)
echo   %AIAC_CONFIG%
echo   %AIAC_TASKS_DIR%\todo.md
echo   %AIAC_TASKS_DIR%\lessons.md
echo.
echo Next steps:
echo   1. Commit AGENTS.md, CLAUDE.md, project.yml, docs\, and .aiac\.
echo   2. Edit .aiac\config.yml to match this project's stack.
echo   3. .aiac\ is host-owned and committed by default. Hosts that prefer
echo      per-developer task state may add '.aiac/tasks/' to .gitignore.
echo   4. Read ai-agent-core\INDEX.md before any change.
echo.
