#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CORE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TEMPLATE_DIR="$CORE_ROOT/template"
TARGET_DIR="$(pwd)"
CORE_JSON="$CORE_ROOT/agent-core.json"

if [[ ! -f "$CORE_JSON" ]]; then
  echo "agent-core.json not found. Aborting."
  exit 1
fi

read_json_value () {
  grep -m 1 "\"$1\"" "$CORE_JSON" | sed -E 's/.*"([^"]+)".*/\1/'
}

VERSION=$(read_json_value "version")
SCHEMA_VERSION=$(read_json_value "schemaVersion")
DESCRIPTION=$(read_json_value "description")

echo ""
echo "Installing Agent Core v$VERSION"
echo "$DESCRIPTION"
echo "Schema version: $SCHEMA_VERSION"
echo ""

fail_if_exists () {
  if [[ -e "$TARGET_DIR/$1" ]]; then
    echo "Error: $1 already exists. Aborting."
    exit 1
  fi
}

fail_if_exists "AGENTS.md"
fail_if_exists "CLAUDE.md"
fail_if_exists "agent-spec"

cp -R "$TEMPLATE_DIR/." "$TARGET_DIR/"

echo "" >> "$TARGET_DIR/AGENTS.md"
echo "---" >> "$TARGET_DIR/AGENTS.md"
echo "Generated by agent-core v$VERSION" >> "$TARGET_DIR/AGENTS.md"

echo "" >> "$TARGET_DIR/CLAUDE.md"
echo "---" >> "$TARGET_DIR/CLAUDE.md"
echo "Generated by agent-core v$VERSION" >> "$TARGET_DIR/CLAUDE.md"

echo ""
echo "✅ Agent Core installed successfully."
echo ""
echo "Next steps:"
echo "1. Commit the generated files."
echo "2. Ensure agents begin with AGENTS.md."
echo ""
