#!/usr/bin/env bash

set -euo pipefail

########################################
# Resolve paths
########################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CORE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SCAFFOLD_DIR="$SCRIPT_DIR/scaffold"
TARGET_DIR="$(pwd)"
CORE_JSON="$CORE_ROOT/ai-agent-core.json"

GENERATED_DIR="$CORE_ROOT/generated"
GENERATED_TASKS_DIR="$GENERATED_DIR/tasks"

########################################
# Validate
########################################

if [[ ! -f "$CORE_JSON" ]]; then
  echo "ai-agent-core.json not found. Aborting."
  exit 1
fi

if [[ ! -d "$SCAFFOLD_DIR" ]]; then
  echo "scaffold directory not found. Aborting."
  exit 1
fi

########################################
# Read JSON (dependency-free)
########################################

read_json_value () {
  grep -m 1 "\"$1\"" "$CORE_JSON" | sed -E 's/.*"([^"]+)".*/\1/'
}

VERSION=$(read_json_value "version")
SCHEMA_VERSION=$(read_json_value "schemaVersion")
DESCRIPTION=$(read_json_value "description")

########################################
# Banner
########################################

echo ""
echo "Installing AI Agent Core v$VERSION"
echo "$DESCRIPTION"
echo "Schema version: $SCHEMA_VERSION"
echo ""

########################################
# Prevent overwrite (parent only)
########################################
#
# Only AGENTS.md and CLAUDE.md are written to the host project root.
# Runtime state (tasks/) is created inside ai-agent-core/generated/, which
# is gitignored by ai-agent-core itself.
########################################

fail_if_exists () {
  if [[ -e "$TARGET_DIR/$1" ]]; then
    echo "Error: $1 already exists. Aborting."
    exit 1
  fi
}

fail_if_exists "AGENTS.md"
fail_if_exists "CLAUDE.md"

########################################
# Install entrypoints to host project root
########################################

cp "$SCAFFOLD_DIR/AGENTS.md" "$TARGET_DIR/AGENTS.md"
cp "$SCAFFOLD_DIR/CLAUDE.md" "$TARGET_DIR/CLAUDE.md"

########################################
# Provision runtime task surface inside ai-agent-core/generated/
########################################
#
# tasks/todo.md and tasks/lessons.md live with ai-agent-core, not the host
# project, so the host's working tree stays clean. They are created only
# when missing — existing state is never overwritten.
########################################

mkdir -p "$GENERATED_TASKS_DIR"

if [[ ! -e "$GENERATED_TASKS_DIR/todo.md" ]]; then
  cp "$SCAFFOLD_DIR/tasks/todo.md" "$GENERATED_TASKS_DIR/todo.md"
fi

if [[ ! -e "$GENERATED_TASKS_DIR/lessons.md" ]]; then
  cp "$SCAFFOLD_DIR/tasks/lessons.md" "$GENERATED_TASKS_DIR/lessons.md"
fi

########################################
# Stamp generated entrypoints
########################################

{
  echo ""
  echo "---"
  echo "Generated by ai-agent-core v$VERSION"
} >> "$TARGET_DIR/AGENTS.md"

{
  echo ""
  echo "---"
  echo "Generated by ai-agent-core v$VERSION"
} >> "$TARGET_DIR/CLAUDE.md"

########################################
# Done
########################################

echo ""
echo "AI Agent Core installed."
echo ""
echo "Wrote:"
echo "  $TARGET_DIR/AGENTS.md"
echo "  $TARGET_DIR/CLAUDE.md"
echo "  $GENERATED_TASKS_DIR/todo.md"
echo "  $GENERATED_TASKS_DIR/lessons.md"
echo ""
echo "Next steps:"
echo "  1. Commit AGENTS.md and CLAUDE.md."
echo "  2. ai-agent-core/generated/ is intentionally gitignored — do not commit."
echo "  3. Read ai-agent-core/INDEX.md before any change."
echo ""
