#!/usr/bin/env bash

set -euo pipefail

########################################
# Resolve Paths
########################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CORE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SCAFFOLD_DIR="$SCRIPT_DIR/scaffold"
TARGET_DIR="$(pwd)"
CORE_JSON="$CORE_ROOT/agent-core.json"

########################################
# Validate
########################################

if [[ ! -f "$CORE_JSON" ]]; then
  echo "agent-core.json not found. Aborting."
  exit 1
fi

if [[ ! -d "$SCAFFOLD_DIR" ]]; then
  echo "scaffold directory not found. Aborting."
  exit 1
fi

########################################
# Read JSON (dependency-free)
########################################

read_json_value () {
  grep -m 1 "\"$1\"" "$CORE_JSON" | sed -E 's/.*"([^"]+)".*/\1/'
}

VERSION=$(read_json_value "version")
SCHEMA_VERSION=$(read_json_value "schemaVersion")
DESCRIPTION=$(read_json_value "description")

########################################
# Banner
########################################

echo ""
echo "Installing Agent Core v$VERSION"
echo "$DESCRIPTION"
echo "Schema version: $SCHEMA_VERSION"
echo ""

########################################
# Prevent Overwrite
########################################

fail_if_exists () {
  if [[ -e "$TARGET_DIR/$1" ]]; then
    echo "Error: $1 already exists. Aborting."
    exit 1
  fi
}

fail_if_exists "AGENTS.md"
fail_if_exists "CLAUDE.md"
fail_if_exists "agent-input"
fail_if_exists "tasks"

########################################
# Copy Scaffold (dotfile-safe)
########################################

cp -R "$SCAFFOLD_DIR/." "$TARGET_DIR/"

########################################
# Stamp Generated Files
########################################

echo "" >> "$TARGET_DIR/AGENTS.md"
echo "---" >> "$TARGET_DIR/AGENTS.md"
echo "Generated by agent-core v$VERSION" >> "$TARGET_DIR/AGENTS.md"

echo "" >> "$TARGET_DIR/CLAUDE.md"
echo "---" >> "$TARGET_DIR/CLAUDE.md"
echo "Generated by agent-core v$VERSION" >> "$TARGET_DIR/CLAUDE.md"

########################################
# Success
########################################

echo ""
echo "✅ Agent Core installed successfully."
echo ""
echo "Next steps:"
echo "1. Commit the generated files."
echo "2. Ensure agents begin with AGENTS.md."
echo ""
